apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-client
  labels:
    app: messaging-client
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-client
      type: pod
  template:
    metadata:
      labels:
        app: messaging-client
        type: pod
    spec:
      containers:
      - name: messaging-client
        image: syamsuldocker/syamsulapp-client:v0.0.3
        ports:
        - containerPort: 80
      #   volumeMounts:
      #     - name: messaging-client-configmap
      #       mountPath: /etc/nginx/conf.d

      # volumes:
      #   - name: messaging-client-configmap
      #     configMap:
      #       name: messaging-client-configmap
