apiVersion: v1
kind: Service
metadata:
  name: messaging-client-nodeport
  labels:
    app: messaging-client
    type: nodeport
spec:
  type: NodePort
  selector:
    app: messaging-client
    type: pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80