apiVersion: v1
kind: Service
metadata:
  name: messaging-api-clusterip
  labels:
    app: messaging-api
    type: clusterip
spec:
  selector:
    app: messaging-api
    type: pod
  ports:
    - protocol: TCP
      port: 5000 # container port
      targetPort: 5000 # service port