apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-api-deployment
  labels:
    app: messaging-api
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-api
      type: pod
  template:
    metadata:
      labels:
        app: messaging-api
        type: pod
    spec:
      containers:
      - name: messaging-api
        image: syamsuldocker/syamsulapp-http:v0.0.8
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: messaging-api-secret
        - configMapRef:
            name: messaging-api-configmap
        command: ["/bin/bash"]
        args: ["-c", "./messaging-api"]

          
                
