apiVersion: v1
kind: Service
metadata:
  name: messaging-api-nodeport
  labels:
    app: messaging-api
    type: nodeport
spec:
  type: NodePort
  selector:
    app: messaging-api
    type: pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001