apiVersion: v1
kind: Service
metadata:
  name: messaging-websocket-clusterip
  labels:
    app: messaging-websocket
    type: clusterip
spec:
  selector:
    app: messaging-websocket
    type: pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000