apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-websocket-deployment
  labels:
    app: messaging-websocket
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-websocket
      type: pod
  template:
    metadata:
      labels:
        app: messaging-websocket
        type: pod
    spec:
      containers:
      - name: messaging-websocket
        image: syamsuldocker/messaging-websocket:v0.0.1
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: messaging-websocket-secret
        command: ["/bin/bash"]
        args: ["-c", "node main.js"] 

                
