apiVersion: v1
kind: Service
metadata:
  name: messaging-websocket-nodeport
  labels:
    app: messaging-websocket
    type: nodeport
spec:
  type: NodePort
  selector:
    app: messaging-websocket
    type: pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003