apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
  labels:
    app: postgres
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: postgres
    type: pod
  ports:
    - protocol: TCP
      port: 5432 # container port
      targetPort: 5432 #service port