apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      type: pod
  template:
    metadata:
      labels:
        app: postgres
        type: pod
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: POSTGRES_PASSWORD
