apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  labels:
    app: postgres
    type: nodeport
spec:
  type: NodePort
  selector:
    app: postgres
    type: pod
  ports:
    - protocol: TCP
      port: 5432 #container port
      # targetPort: 5432 #service port
      nodePort: 30000 #open port