apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      type: pod
  template:
    metadata:
      labels:
        app: mongo
        type: pod
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongo-secret
