apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
  labels:
    app: mongo
    type: nodeport
spec:
  type: NodePort
  selector:
    app: mongo
    type: pod
  ports:
    - protocol: TCP
      port: 27017 #container port
      targetPort: 27017 #service port
      nodePort: 30001 #open port