apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  labels:
    app: redis
    type: clusterip
spec:
  selector:
    app: redis
    type: pod
  ports:
    - protocol: TCP
      port: 6379 #container port
      targetPort: 6379 #servce port