# this is an example file, configure it as you need, it serve as env file inside kubernetes pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  .env: |
    #!/bin/bash
    export REDIS_PASSWORD=
