apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      type: pod
  template:
    metadata:
      labels:
        app: redis
        type: pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-configmap
            mountPath: /myconfig
            readOnly: false
        command: ["/bin/bash"]
        args: ["-c", "source /myconfig/.env && redis-server --requirepass $REDIS_PASSWORD"]

      volumes:
        - name: redis-configmap
          configMap:
            name: redis-configmap
