apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    app: redis
    type: nodeport
spec:
  type: NodePort
  selector:
    app: redis
    type: pod
  ports:
    - protocol: TCP
      port: 6379 #container port
      targetPort: 6379 #service port
      nodePort: 30003 #node port